## Question 1:
Function `parse_census_tracts` doesn't work?

In [32]:
incidents, pop_data, housing_data, age_data = load_data()

Loading data...
  Structure fire incidents: 3,176
  Incidents with tract data: 3,176 (100.0%)
  Census tracts with population: 471
  Census tracts with housing: 471
  Census tracts with building age: 471

In [34]:
incidents.head()

,incident_number,calendaryear,month,incdate,call_type,problem,responsearea,jurisdiction,prioritydescription,council_district,location,longitude,latitude,census_tracts,tract_list
0,22000037,2022,Jan,01/01/2022 12:00:00 AM,Fire,BOX -Structure Fire,00-2306,AFD,1F,4,"(-97.692635,30.364969)",-97.692635,30.364969,['410'],[410]
1,22000085,2022,Jan,01/01/2022 12:00:00 AM,Fire,BOXS - Still Box Alarm,00-1407,AFD,1F,4,"(-97.714795,30.316076)",-97.714795,30.316076,['15.03'],[15.03]
2,22000122,2022,Jan,01/01/2022 12:00:00 AM,Fire,BOXL- Structure Fire,00-4104,AFD,1F,1,"(-97.612957,30.372331)",-97.612957,30.372331,['449'],[449]
3,22000252,2022,Jan,01/01/2022 12:00:00 AM,Fire,BOX -Structure Fire,00-1709,AFD,1F,3,"(-97.765376,30.213776)",-97.765376,30.213776,['24.03'],[24.03]
4,22000440,2022,Jan,01/01/2022 12:00:00 AM,Fire,BOX -Structure Fire,00-2306,AFD,1F,4,"(-97.691949,30.359055)",-97.691949,30.359055,['431'],[431]

In [37]:
incidents[['incident_number', 'census_tracts', 'tract_list']][incidents['tract_list'].apply(len) > 1].head()

     incident_number             census_tracts          tract_list
34          22003662          ['2.04', '2.03']        [2.04, 2.03]
54          22007278        ['23.24', '23.26']      [23.24, 23.26]
69          22009976            ['313', '319']          [313, 319]
85          22011294        ['13.08', '13.07']      [13.08, 13.07]
100         22012115  ['6.06', '6.05', '2.04']  [6.06, 6.05, 2.04]

In [39]:
import geopandas as gpd
tracts = gpd.read_file('../raw_data/tl_2023_48_tract.shp')
tracts.head()

,STATEFP,COUNTYFP,TRACTCE,GEOID,GEOIDFQ,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,48,157,674100,48157674100,1400000US48157674100,6741,Census Tract 6741,G5020,S,4170615,0,+29.5791692,-095.5995891,"POLYGON ((-95.61467 29.57828, -95.61339 29.578..."
1,48,157,674200,48157674200,1400000US48157674200,6742,Census Tract 6742,G5020,S,5800266,189859,+29.5713421,-095.6222174,"POLYGON ((-95.63989 29.58625, -95.63974 29.586..."
2,48,441,013501,48441013501,1400000US48441013501,135.01,Census Tract 135.01,G5020,S,866463520,4539887,+32.1806265,-099.9286588,"POLYGON ((-100.15192 32.08412, -100.15188 32.0..."
3,48,441,013602,48441013602,1400000US48441013602,136.02,Census Tract 136.02,G5020,S,665184779,422010,+32.3991003,-100.0146292,"POLYGON ((-100.14955 32.2816, -100.1495 32.286..."
4,48,441,013601,48441013601,1400000US48441013601,136.01,Census Tract 136.01,G5020,S,36492558,0,+32.4639334,-100.0041804,"POLYGON ((-100.03974 32.48854, -100.03064 32.4..."

In [46]:
census_df = pd.read_csv("../raw_data/census_housing.csv", dtype={'tract': str})

In [48]:
census_df.head()

,Total,"1-unit, detached","1-unit, attached",2 units,3-4 units,5-9 units,10-19 units,20-49 units,50 or more units,Mobile home,"Boat, RV, van",Census tract name,state,county,tract
0,1339,471,47,31,41,187,176,69,300,17,0,Census Tract 101; Hays County; Texas,48,209,010100
1,915,217,56,0,63,79,81,48,346,25,0,Census Tract 102; Hays County; Texas,48,209,010200
2,1939,638,42,81,230,147,203,144,217,237,0,Census Tract 103.02; Hays County; Texas,48,209,010302
3,2854,401,56,49,427,168,1068,203,394,88,0,Census Tract 103.05; Hays County; Texas,48,209,010305
4,1516,123,0,62,15,105,156,161,152,742,0,Census Tract 103.06; Hays County; Texas,48,209,010306